### ISSUE TITLE
A mob doesn't ride minecart

### ISSUE THREAD

**Issue by RunqRun** [Dreeam-qwq/Leaf#10]
I got some reports from players who joined the server.
They said "Maybe, all mobs didn't ride minecart".

Please check it and test.

Server Version: leaf-1.20.2 (latest)

**Comment by Dreeam-qwq** [comment]
temporarily "fixed" in [7c1e327](https://github.com/Winds-Studio/Leaf/actions/runs/6522902370)

**Comment by RunqRun** [comment]
Thanks for the fixed.

**Comment by Dreeam-qwq** [comment]
Fixed in 662cf20316441d0cc58bd44cadb7ab94edd0d4d8
