### ISSUE TITLE
【漏洞】Trchat 在1.21.1无法正常使用。

### ISSUE THREAD

**Issue by JellyBubb1e** [Dreeam-qwq/Leaf#107]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What behaviour is observed?

在purpur端，Trchat能正常启动，且能正常使用发送消息，切换到leaf端后，Trchat虽然能正常启动，但是无法显示玩家消息。
[日志点我](https://mclo.gs/CuIISp4)

### Expected behaviour

Trchat 能正常使用，能够显示玩家消息。

### To Reproduce

1. 下载leaf端
2. 将trchat 移入plugins文件夹
3. 用玩家身份进服，发送消息，发现无事发生，后台报错

### Plugin list

AdvancedServerList-Paper-4.12.0.jar
AntiPopup-9.2.jar
AuthMe-5.7.0-FORK-Universal.jar
blockprot-spigot-1.2.1-all.jar
CoreProtect-22.4.jar
Citizens-2.0.35-b3501.jar
CmdCooldown-1.0.jar
CMI-9.7.5.3.jar
CMILib1.5.1.1.jar
CrazyAuctions-1.6.1.jar
DivinityEconomy-3.4.3.jar
Duels-Optimised-3.0-BETA.jar
eco-6.73.4-all.jar
EcoEnchants v12.18.0.jar
EditableStands-1.3.1.jar
Elevator.jar
EnderDragon-2.5.4.jar
GiftBox.jar
GSit-1.10.0.jar
HerdsPanic-1.1.jar
ImageFireworksPro-1.1.6.jar
ImageFrame-1.7.10.0.jar
images-2.5.0.jar
InteractionVisualizer-1.18.11.0.jar
InteractiveChat-4.2.12.0.jar
LotterySix-1.10.16.0.jar
LuckPerms-Bukkit-5.4.139.jar
PlaceholderAPI-2.11.7-DEV-200.jar
PlayerDoll-1.35.jar
PlugManX-2.4.1.jar
PocketGames.jar
ProtocolLib.jar
QuickShop-Hikari-6.2.0.7.jar
RealScale-1.1-SNAPSHOT.jar
Residence5.1.6.0.jar
SeeMore-1.0.2.jar
Shopkeepers-2.23.1-SNAPSHOT.jar
SkinsRestorer.jar
Skript-2.9.1.jar
Skript-AnvilGUI-1.8.jar
TAB v4.1.7.jar
TrChat-2.2.0-beta1.jar
UltimateTimber-3.1.1.jar
UltraCosmetics-3.7-RELEASE.jar
Vault.jar
Vulcan-2.9.0.jar
WhereMyFrame-1.0.jar
worldedit-bukkit-7.3.6.jar
WorldListTrashCan-5.1.3.jar
zmenu-1.0.3.3.jar
[bukkit_spigot_paper]AllMusic_Server-3.1.8-all.jar

### Leaf Version

Leaf version 1.21.1-DEV-ver/1.21.1@9aafe04

**Comment by Dreeam-qwq** [comment]
请确保Leaf版本是最新的，并且删掉cache/taboolib文件夹，重启服试试

**Comment by JellyBubb1e** [comment]
在最新版本已解决。😁
