### ISSUE TITLE
Cactus and minecart

### ISSUE THREAD

**Issue by Sheeqzy** [Dreeam-qwq/Leaf#11]
Latest leaf 1.20.1

Most of the time when cactus grows it grows in  between  2 blocks or a block with is not happening in vanilla minecraft/paper 
![javaw_Sx1R15DLdY](https://github.com/Winds-Studio/Leaf/assets/88279163/4cc0ff90-b39c-4fb2-9dce-617f5932022d)
![javaw_QeGGjPDUO2](https://github.com/Winds-Studio/Leaf/assets/88279163/9642079f-a54b-46b2-a504-f01850769041)
![javaw_wGKr67sOhm](https://github.com/Winds-Studio/Leaf/assets/88279163/11c62136-ea36-45ea-bbe3-b9dc98b856bc)

and  villager and endermite (and probably all the mobs) wont enter the minecart.

if you fix it please update it in 1.20.1 thank you

**Comment by Dreeam-qwq** [comment]
Finished and you can download in https://github.com/Winds-Studio/Leaf/releases/tag/ver-1.20.1

**Comment by Dreeam-qwq** [comment]
Closed since the cactus issue caused by wrong server core configuration.
