### ISSUE TITLE
[1.21] Login error

### ISSUE THREAD

**Issue by scar-day** [Dreeam-qwq/Leaf#113]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### What behaviour is observed?

An error occurs

### Expected behaviour

Login error occurs

### To Reproduce

1.Start server
2.join to server
3.an error occurs, sometimes not immediately

### Plugin list

[15:28:58 INFO]: Paper Plugins: (0):
[15:28:58 INFO]: Bukkit Plugins: (15):
[15:28:58 INFO]:  - DecentHolograms, DeluxeHubReloaded, emotecraft, FastAsyncWorldEdit, Images, LPX, PlaceholderAPI, ProAntiTab, ProtocolLib, TAB
[15:28:58 INFO]:  ViaBackwards, ViaVersion, VoidTeleport, WorldGuard, ZNPCsPlus

### Leaf Version

This server is running Leaf version 1.21-DEV-ver/1.21@ee6983a 

### Error log (if applicable)

https://mclo.gs/fg0TYSJ https://i.imgur.com/8wbhuNB.png

### Configuration

https://mclo.gs/6J1qRkn

**Comment by Dreeam-qwq** [comment]
Try update your ViaBackwards and ViaVersion to latest build from their ci site.

And you should use Leaf 1.21.1, this issue also is not Leaf's issue

**Comment by scar-day** [comment]
> Try update your ViaBackwards and ViaVersion to latest build from their ci site.
> 
> And you should use Leaf 1.21.1, this issue also is not Leaf's issue

Okey...

**Comment by scar-day** [comment]
> Try update your ViaBackwards and ViaVersion to latest build from their ci site.
> 
> And you should use Leaf 1.21.1, this issue also is not Leaf's issue

doesn't work, even deleted ViaBackwards.

![image](https://github.com/user-attachments/assets/4628555c-933b-4c21-9ad6-baf10eb99167)

players can log in through.

**Comment by Dreeam-qwq** [comment]
> > Try update your ViaBackwards and ViaVersion to latest build from their ci site.
> > And you should use Leaf 1.21.1, this issue also is not Leaf's issue
> 
> doesn't work, even deleted ViaBackwards.
> 
> ![image](https://private-user-images.githubusercontent.com/93832519/367385288-4628555c-933b-4c21-9ad6-baf10eb99167.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyNTE4MTAsIm5iZiI6MTcyNjI1MTUxMCwicGF0aCI6Ii85MzgzMjUxOS8zNjczODUyODgtNDYyODU1NWMtOTMzYi00YzIxLTlhZDYtYmFmMTBlYjk5MTY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEzVDE4MTgzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU2YmIwOTc2NjQ4MjZjMzg1YTlmMDQyMTAwY2VkZTQzOTQxMzI3Y2MwOWY3YmFmY2I1Y2M5MDIwMjQ1ZjgyZjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pcc4B2XDp26Ps7mt4n0OcMZEgKVCO9b8Zr0HZhgTvUs)
> 
> players can log in through.

Use 1.21.1. 1.21 is not supported

**Comment by scar-day** [comment]
> > > Try update your ViaBackwards and ViaVersion to latest build from their ci site.
> > > And you should use Leaf 1.21.1, this issue also is not Leaf's issue
> > 
> > 
> > doesn't work, even deleted ViaBackwards.
> > ![image](https://private-user-images.githubusercontent.com/93832519/367385288-4628555c-933b-4c21-9ad6-baf10eb99167.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyNTE4MTAsIm5iZiI6MTcyNjI1MTUxMCwicGF0aCI6Ii85MzgzMjUxOS8zNjczODUyODgtNDYyODU1NWMtOTMzYi00YzIxLTlhZDYtYmFmMTBlYjk5MTY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEzVDE4MTgzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU2YmIwOTc2NjQ4MjZjMzg1YTlmMDQyMTAwY2VkZTQzOTQxMzI3Y2MwOWY3YmFmY2I1Y2M5MDIwMjQ1ZjgyZjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pcc4B2XDp26Ps7mt4n0OcMZEgKVCO9b8Zr0HZhgTvUs)
> > players can log in through.
> 
> Use 1.21.1. 1.21 is not supported

I use 1.21.1
![image](https://github.com/user-attachments/assets/08671288-bcbe-4fb6-9430-3c9ade2cac62)

**Comment by Dreeam-qwq** [comment]
> > > > Try update your ViaBackwards and ViaVersion to latest build from their ci site.
> > > > And you should use Leaf 1.21.1, this issue also is not Leaf's issue
> > > 
> > > 
> > > doesn't work, even deleted ViaBackwards.
> > > ![image](https://private-user-images.githubusercontent.com/93832519/367385288-4628555c-933b-4c21-9ad6-baf10eb99167.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyNTE4MTAsIm5iZiI6MTcyNjI1MTUxMCwicGF0aCI6Ii85MzgzMjUxOS8zNjczODUyODgtNDYyODU1NWMtOTMzYi00YzIxLTlhZDYtYmFmMTBlYjk5MTY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEzVDE4MTgzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU2YmIwOTc2NjQ4MjZjMzg1YTlmMDQyMTAwY2VkZTQzOTQxMzI3Y2MwOWY3YmFmY2I1Y2M5MDIwMjQ1ZjgyZjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pcc4B2XDp26Ps7mt4n0OcMZEgKVCO9b8Zr0HZhgTvUs)
> > > players can log in through.
> > 
> > 
> > Use 1.21.1. 1.21 is not supported
> 
> I use 1.21.1 ![image](https://private-user-images.githubusercontent.com/93832519/367508190-08671288-bcbe-4fb6-9430-3c9ade2cac62.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYzMTI1NjEsIm5iZiI6MTcyNjMxMjI2MSwicGF0aCI6Ii85MzgzMjUxOS8zNjc1MDgxOTAtMDg2NzEyODgtYmNiZS00ZmI2LTk0MzAtM2M5YWRlMmNhYzYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE0VDExMTEwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1Y2ZhMWRjZTI2MWU1ZTg4MTUxODk3MWU3YzA2OWU1YjM3YzBhZDZmM2IwOTIyMmIzMDIwYTljOTNhNjhkYzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4u9Peuk49WMCur3UoAgw05nkEtk5EYjfSjP62waHbkY)

You are 6 versions behind

**Comment by Dreeam-qwq** [comment]
Closed since can not replicate. Welcome to reopen it if you met this issue on latest Leaf 1.21.1 (and also provide steps to replicate and link of spark profiler).
