### ISSUE TITLE
[Important] Citizens and other NPC plugins not working with (Fake) Player type.

### ISSUE THREAD

**Issue by softy-oniguru** [Dreeam-qwq/Leaf#114]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What behaviour is observed?

[1/4 chances: Crash Error] The player cannot be spawned in the world
[every chances: Nothing] The NPC is not rendered for the player, no one sees it.

### Expected behaviour

when NPC's type is "player", NPC can't be rendered for player (maybe for non-packet entity?)

### To Reproduce

1. Install Citizens plugin on server with Leaf
2. Create a new npc (/npc create <npcname> --type player)

### Plugin list

[10:42:30 INFO]: Paper Plugins: (0):
[10:42:30 INFO]: Bukkit Plugins: (1):
[10:42:30 INFO]:  - Citizens

### Leaf Version

Leaf 1.21.1-DEV-ver/1.21.1@f1c8332

**Comment by Taiyou06** [comment]
do you have async entity tracker on?
if it is on does the compat mode on?

**Comment by softy-oniguru** [comment]
> do you have async entity tracker on? if it is on does the compat mode on?

yes, my config: https://api.mclo.gs/1/raw/ClOEGD9
up to a certain point, everything worked, but apparently some kind of update happened and it stopped working.

**Comment by Taiyou06** [comment]
I would recommend disabling async tracker till further notice.

**Comment by Dreeam-qwq** [comment]
Can't replicate, player type NPC of Citizens can render normally when **async tracker and compat mode was on**.

How did you test? And which other NPC plugins? And `[1/4 chances: Crash Error] The player cannot be spawned in the world` without any error?
