### ISSUE TITLE
Question/Suggestion: Merging Gale and Leaf

### ISSUE THREAD

**Issue by ghost** [Dreeam-qwq/Leaf#116]
### What feature do you want to see added?

Historically, Gale has been a separate project with its own maintainers. Currently, you are the only maintainer of Gale and, in fact, you've downstream-forked Gale to provide updates. My question is:

Why don't you merge Gale patches into Leaf?

This would
1. Prevent general confusion about upstream. 
2. Reduce horrible upstream fork chain at least by one. 
3. Ease maintenance by a bit.

**Comment by Dreeam-qwq** [comment]
Most of my intention is just waiting for Martijn back, unless he announces he will not maintain Gale anymore or archive the Gale repo.

Martijn is the owner/creator of Gale, but he suddenly disappeared from the Internet and also stopped maintaining Gale around 1 year ago. We couldn't contact him through Gale's discord or his discord dm, no response. Based on some understanding to him, Martijn is busy with reality work for now (he also mentioned this in his another discord server, and then disappeared again).

Thus I decided to continue maintain Gale (mostly just keep updating upstream) and keep it. And once he comes back, maybe my fork can help him follow upstream? Or he can sync to upstream by himself. (((

For 1, you can think Leaf is a Gale fork, or Paper fork, both statements are acceptable.
For 2, I don't think this fork chain has any problem, It still can be seen as "one fork" essentially.
For 3, I wish more people could contribute to Leaf and it can make my maintenance more easier (

**Comment by ghost** [comment]
Ok, if you want to wait until the original author comes back, it's a good idea not to merge patches for sure. However, it would be better to update references to Gale to your downstream fork for the time being to let people know where's that magic "Gale 1.21" is located. Still however, if the author won't come back in some time, say a year or half a year, it would be much better to merge patches.

**Comment by Dreeam-qwq** [comment]
> Ok, if you want to wait until the original author comes back, it's a good idea not to merge patches for sure. However, it would be better to update references to Gale to your downstream fork for the time being to let people know where's that magic "Gale 1.21" is located. Still however, if the author won't come back in some time, say a year or half a year, it would be much better to merge patches.

Okay, will do during this weekend

**Comment by Dreeam-qwq** [comment]
Updated in https://github.com/Winds-Studio/Leaf/commit/356b3b42be4f8aab42c2c25c5638f0042376d2a3
