### ISSUE TITLE
1.21.1无法使用Citizens创建npc

### ISSUE THREAD

**Issue by maomaokeai** [Dreeam-qwq/Leaf#119]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What behaviour is observed?

我从leaf1.21更新到leaf1.21.1，发现Citizens（版本2.0.35-b3568）无法使用，Citizens所有命令以及功能正常，无任何报错，创建npc成功，但是无任何显示，没有交互，地图上完全没有npc

### Expected behaviour

切换到leaf1.21正常，paper1.21.1最新版本正常，其他版本没有试验

### To Reproduce

百分百重现，非偶发性

### Spark profiler link

https://spark.lucko.me/GZz2P5M8VO

**Comment by Dreeam-qwq** [comment]
和 https://github.com/Winds-Studio/Leaf/issues/114 重复

leaf配置(config/leaf-global.yml)里打开async-entity-tracker.compat-mode
