### ISSUE TITLE
Is it possible to somehow optimize the work of data packs?

### ISSUE THREAD

**Issue by DonorKrovi** [Dreeam-qwq/Leaf#12]
Is it possible to somehow optimize the work of data packs?

**Comment by Dreeam-qwq** [comment]
You can provide related spark profiler report. So that we can easily find out which parts of the datapack cause lag.

**Comment by Dreeam-qwq** [comment]
Not possible, unless rewrite many things? I guess.

I recommend to use plugin with similar features instead.
