### ISSUE TITLE
Automatically push Maven artifacts

### ISSUE THREAD

**Issue by ghost** [Dreeam-qwq/Leaf#120]
### What feature do you want to see added?

Maven artifacts are often outdated. This leads to dev bundles and APIs being outdated and not supporting latest Paper and Purpur features, despite them being present in implementation.

**Comment by Dreeam-qwq** [comment]
Added in https://github.com/Winds-Studio/Leaf/commit/aba0995736d94ac4c19d33108b881d76f1387a5a
