### ISSUE TITLE
更新Leaf核心后SkinsRestorer和EcoEnchants的GUI无法打开

### ISSUE THREAD

**Issue by CaesarGalahad** [Dreeam-qwq/Leaf#121]
### 是否已存在相关问题？

- [X] 我已经浏览过Issue，并确保汇报的不是已知问题

### 问题描述

将Leaf核心更新至1.21.1-DEV-ver/1.21.1@e62b6fc (2024-09-22T10:46:44Z) 后
SkinsRestorer和EcoEnchants的GUI无法打开
但在1.21.1-DEV-ver/1.21.1@cfdd5f1 (2024-08-28T21:19:59Z)版本可以正常打开

BUGLOG INFO
https://mclo.gs/e4h62ME

FULLLOG INFO
https://mclo.gs/CbClYXb

### 所期望的行为

已排查非插件本身问题
插件已更新至最新版
近期没有添加新插件
仅更新了Leaf核心

### 如何复现？

将Leaf核心更新至1.21.1-DEV-ver/1.21.1@e62b6fc (2024-09-22T10:46:44Z) 后
SkinsRestorer和EcoEnchants的GUI无法打开

### Spark profiler 链接

https://spark.lucko.me/vN3dkkii4K

### 错误日志 (如存在)

https://mclo.gs/e4h62ME

**Comment by Dreeam-qwq** [comment]
上游Spigot做的改动，不是Leaf的问题
更新你的SkinsRestorer https://ci.codemc.io/job/SkinsRestorer/job/SkinsRestorer/
EcoEnchants没更新这个，等吧

**Comment by CaesarGalahad** [comment]
收到 谢谢
