### ISSUE TITLE
插件 AdvancedPets, Guilds, LiteSignIn 与头颅有关的操作异常

### ISSUE THREAD

**Issue by miguotw** [Dreeam-qwq/Leaf#123]
### 自我检查表

- [x] 我已经浏览过Issue, 并确保汇报的不是已知问题
- [X] 我正在使用从 https://github.com/Winds-Studio/Leaf/releases 下载的最新 Leaf 构建
- [X] 我无法在 [Purpur 最新构建](https://purpurmc.org/) 上复现此问题
- [ ] 我勾选了所有框, 因为我根本就没仔细看他们是什么

### 插件 AdvancedPets, Guilds, LiteSignIn 与头颅有关的操作异常

**AdvancedPets**

1. 输入 `/advancedpets:pets` 打开宠物菜单时，头颅无法正确显示
![屏幕截图 2024-09-25 042250](https://github.com/user-attachments/assets/d4f78237-312d-4b5c-b3da-f298c2474b8f)

2. 然后点击一个宠物尝试召唤时触发错误
(详见 log 文件 `[04:14:47 WARN]: java.lang.IllegalArgumentException: Can not set ...` )

**Guilds**

- 输入 `/guilds list` 尝试列出所有公会时未出现 GUI，同时控制台报告了错误
(详见 log 文件 `[04:15:15 ERROR]: [global] TaskChain Exception on ...` )

**LiteSignIn**

- 输入 `/signin gui` 打开菜单时，头颅无法正确显示 (控制台没有报告错误)
![屏幕截图 2024-09-25 042330](https://github.com/user-attachments/assets/4269d1f7-1ed0-4c54-8697-a2e0b4b5898a)

### 所期望的行为

**AdvancedPets**

1. 输入 `/advancedpets:pets` 打开宠物菜单时，头颅可以正确显示
![屏幕截图 2024-09-25 043632](https://github.com/user-attachments/assets/2f2965f0-d849-49ab-8434-09790b439665)

2. 然后点击一个宠物尝试召唤时能够正常召唤
![屏幕截图 2024-09-25 043745](https://github.com/user-attachments/assets/7fd90460-dfe6-4c4a-8d7f-af9c746f3e68)

**Guilds**

- 输入 `/guilds list` 时，可以正确打开
![屏幕截图 2024-09-25 044011](https://github.com/user-attachments/assets/c9f1a984-f7ee-4ad7-9e7b-1ac82b2c74c0)

**LiteSignIn**

- 输入 `/signin gui` 时，头颅可以正确显示
![屏幕截图 2024-09-25 044141](https://github.com/user-attachments/assets/b7950388-962b-495b-be51-823964a24ccf)

### 如何复现？

1. 进入服务器
2. 输入命令 `/advancedpets:pets`
3. 控制台出现报错
4. 输入命令 `/guilds list`
5. 控制台出现报错
6. 输入命令 `/signin gui`
7. 控制台无报错，但未正确显示

### Spark profiler 链接

https://spark.lucko.me/JY3ZHkcYuE

### 错误日志 (如存在)

https://mclo.gs/rF5bX40

**Comment by Dreeam-qwq** [comment]
和 https://github.com/Winds-Studio/Leaf/issues/121 重复
Paper那边相关回答 https://github.com/PaperMC/Paper/issues/11428#issuecomment-2366830328

不是Leaf的问题，在Spigot/Paper/Purpur上都一样，等插件作者自己更新, 兼容

**Comment by miguotw** [comment]
我犯了一个错误...
因为启动脚本设置错误的缘故，我一直认为我使用的是 purpur 2311 ，但实际上是更为老旧的 purpur 2284
