### ISSUE TITLE
新增 NoChatReport ”安全服务器“ 标识协议

### ISSUE THREAD

**Issue by Radiation-pi** [Dreeam-qwq/Leaf#127]
### 你想加入什么功能？

leaf 已经有了安全聊天，理论上不需要 NoChatReport 之类的插件，请求加入 NoChatReport 的协议，以便让玩家 ping 服务器时收到 ”安全服务器“ 标识。

![image](https://github.com/user-attachments/assets/5b59914b-0426-4c80-be8c-5180f83b2b4d)

具体操作参考：
https://github.com/Aizistral-Studios/No-Chat-Reports/wiki/How-to-Get-Safe-Server-Status

**Comment by Dreeam-qwq** [comment]
已在 https://github.com/Winds-Studio/Leaf/commit/dfcae93fa7e765de3e086a0badc54323afd2e1a8 加入, 在Leaf配置里关掉聊天签名, 然后客户端装了No Chat Report就可以看到了

**Comment by Radiation-pi** [comment]
Good jeb_ !
