### ISSUE TITLE
Multithread Entities

### ISSUE THREAD

**Issue by wildmaster84** [Dreeam-qwq/Leaf#128]
### What feature do you want to see added?

I have been testing around with how the server handles a large load of entities and as i observed i noticed that as it does not block the main thread it still can cause a crash when theres a ton of entities. I think a simple fix for this would be making a patch to move all entity stuff onto its own thread so the chances of it causing a full server crash it less likely.

**Comment by Dreeam-qwq** [comment]
Multithread entities is not safe, and for a server, it's less possible to have a **very large** load of entities.

If your server lag, you need to provide spark profiler.

**Comment by Dreeam-qwq** [comment]
Closed as not planned.

But if your server met lag, welcome to send the spark profiler in our [discord server](https://discord.gg/gfgAwdSEuM) or via my discord dm.
