### ISSUE TITLE
Iron farm not working

### ISSUE THREAD

**Issue by RRS-9747** [Dreeam-qwq/Leaf#129]
### Checklist

- [X] I have searched the existing issues
- [ ] I ticked all the boxes without actually reading them
- [X] I am using latest Leaf build from https://github.com/Winds-Studio/Leaf/releases
- [X] I tested and couldn't replicate this issue on [latest Purpur build](https://purpurmc.org/)

### What behaviour is observed?

3 villagers are panicking for a zombie & it should spawn a iron golem. but not doing so

### Expected behaviour

just like normal minecraft behave, when atleast 3 villager panic for a zombie, it should spawn a iron golem

### To Reproduce

no error on console

### Spark profiler link

https://spark.lucko.me/zoA2s9YQKY

**Comment by Dreeam-qwq** [comment]
Try to be  closer to the iron farm machine, or add villager into blacklisted-entities of dab in leaf config or disable the entire dab.

**Comment by RRS-9747** [comment]
fixed
