### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by MVanilla** [Dreeam-qwq/Leaf#145]
### Checklist

- [X] I have searched the existing issues
- [ ] I ticked all the boxes without actually reading them
- [X] I am using latest Leaf build from https://github.com/Winds-Studio/Leaf/releases
- [ ] I tested and couldn't replicate this issue on [latest Purpur build](https://purpurmc.org/)

### What behaviour is observed?

server crash occurred

### Expected behaviour

I never had this crash when I was using Purpur for years, but after switching to Leaf it started crashing within a day.

### To Reproduce

I don't know how to reproduce.

### Spark profiler link

none

### Error log (if applicable)

https://mclo.gs/rupHWif

**Comment by Dreeam-qwq** [comment]
Fixed in https://github.com/Winds-Studio/Leaf/releases/tag/ver-1.21.1
