### ISSUE TITLE
Feature request: Update upstream

### ISSUE THREAD

**Issue by Potothingi** [Dreeam-qwq/Leaf#146]
### What feature do you want to see added?

Paper has been updated to fix important bugs, and even backported to 1.20.6 and 1.20.4.

https://github.com/PaperMC/Paper/commits/ver/1.21.1

[Fix inactive item ticking and remove active tick skipping; fix quit event leave message](https://github.com/PaperMC/Paper/commit/7f7bc17f32c248b1e80e107fcb325ee203354533)
[Fix the fix](https://github.com/PaperMC/Paper/commit/4d2672e1ac157519f921fb0421100aa9ab4856de)

**Comment by Potothingi** [comment]
1.20.6: https://github.com/PaperMC/Paper/commits/ver/1.20.6
1.20.4: https://github.com/PaperMC/Paper/commits/ver/1.20.4

**Comment by PadowYT2** [comment]
1.20.6 is not maintained (but 1.20.4 is somewhat is)

**Comment by Dreeam-qwq** [comment]
You can download latest Leaf for 1.20.4 / 1.20.6 / 1.21.1 from https://github.com/Winds-Studio/Leaf/releases

And we recommend to use Leaf 1.21.1 instead of Leaf 1.20.6, since this version is not supported and will not maintain in the future.
