### ISSUE TITLE
When player is in area, when chunks are not loaded, it drops their elytra from armor on the ground

### ISSUE THREAD

**Issue by pjindras** [Dreeam-qwq/Leaf#151]
### Checklist

- [X] I have searched the existing issues
- [ ] I ticked all the boxes without actually reading them
- [X] I am using latest Leaf build from https://github.com/Winds-Studio/Leaf/releases
- [X] I tested and couldn't replicate this issue on [latest Purpur build](https://purpurmc.org/)

### What behaviour is observed?

When player fly with elytra and arrives into the zone, where the chunks are not loaded, something drops their elytra on the ground, player falls and dies.

Please help, if the issue could be caused by Leaf. It is hard to replicate, but this behavior started happening a few weeks ago.

### Expected behaviour

Player shouldnt drop the elytra.

### To Reproduce

I dont know, but players are reporting this issue, 3/4 issues per week.

### Spark profiler link

https://spark.lucko.me/gxRr95mYM8

**Comment by Dreeam-qwq** [comment]
did you check your AEF config? is `also-remove-elytra-on-low-TPS ` false?

**Comment by pjindras** [comment]
Yes, i forgot that on my paper test server i dont have AEF, my bad
