### ISSUE TITLE
Water bug

### ISSUE THREAD

**Issue by Godl1nk** [Dreeam-qwq/Leaf#152]
### Checklist

- [X] I have searched the existing issues
- [ ] I ticked all the boxes without actually reading them
- [X] I am using latest Leaf build from https://github.com/Winds-Studio/Leaf/releases
- [X] I tested and couldn't replicate this issue on [latest Purpur build](https://purpurmc.org/)

### What behaviour is observed?

Water cannot push any entities, including mobs, item drops, zombie will get burned by sun even while in water

### Expected behaviour

Mobs getting pushed by water

### To Reproduce

Place a water source beside an entity

### Spark profiler link

none

### Error log (if applicable)

none

**Comment by HaHaWTH** [comment]
This issue have been confirmed, we are currently working on addressing this. Please wait patiently( ´▽` ). If this caused a severe impact to your server, you can rollback to commit 2d152a0 to temporarily resolve this.

**Comment by Godl1nk** [comment]
alr ill deal with it and submit a merge request if i fix it

**Comment by Dreeam-qwq** [comment]
Fixed in https://github.com/Winds-Studio/Leaf/commit/0e27d480421620c5e11ce9395d427fb4635edd99

**Comment by Godl1nk** [comment]
so is latest commit now stable to use

**Comment by Dreeam-qwq** [comment]
> so is latest commit now stable to use

You can test.
