### ISSUE TITLE
Cactus growing ?

### ISSUE THREAD

**Issue by Godl1nk** [Dreeam-qwq/Leaf#156]
### Checklist

- [X] I have searched the existing issues
- [ ] I ticked all the boxes without actually reading them
- [X] I am using latest Leaf build from https://github.com/Winds-Studio/Leaf/releases
- [X] I tested and couldn't replicate this issue on [latest Purpur build](https://purpurmc.org/)

### What behaviour is observed?

![image](https://github.com/user-attachments/assets/e9da07a0-6dc0-4e86-a277-bfe76be34105)

### Expected behaviour

if i place a glass pane beside a 2x height cactus it breaks, but it wont break if there is a block there when growing

### To Reproduce

Grow a cactus with glass pane bside it

### Spark profiler link

d

**Comment by Dreeam-qwq** [comment]
Can not replicate, where is your spark profiler?
https://github.com/user-attachments/assets/e38bedaa-d634-4c9f-8359-0da7bc0ecf44

**Comment by Godl1nk** [comment]
alr the bug was causesd by editing growth in spigot.yml
![image](https://github.com/user-attachments/assets/830d6892-6fa5-42ef-afb3-f5a195993d3a)
