### ISSUE TITLE
ModelEngine problem

### ISSUE THREAD

**Issue by mhaas11** [Dreeam-qwq/Leaf#162]
### Checklist

- [X] I have searched the existing issues
- [ ] I ticked all the boxes without actually reading them
- [X] I am using latest Leaf build from https://github.com/Winds-Studio/Leaf/releases
- [X] I tested and couldn't replicate this issue on [latest Purpur build](https://purpurmc.org/)

### What behaviour is observed?

I changed the engine from paper 1.20.2 to Leaf 1.20.2(latest) and when I hit a monster with modelengine it crashes the whole server. I tested on previous engine paper 1.20.2 and on it works perfectly

### Expected behaviour

I can hit mobs without crashing the server

### To Reproduce

Use Leaf 1.20.2
Use ModelEngine4 and MythicMobs
Spawn mob like toro_enderdragon
HIt enderdragon
Immediate server crash

### Spark profiler link

unneeded

### Error log (if applicable)

https://mclo.gs/i0RIhkB

**Comment by Dreeam-qwq** [comment]
Use Leaf 1.21.1 instead, 1.20.2 is not supported.
