### ISSUE TITLE
Question: Optimal number of threads for async-entity-tracker and async-pathfinding?

### ISSUE THREAD

**Issue by Potothingi** [Dreeam-qwq/Leaf#167]
### What feature do you want to see added?

What is the appropriate number of threads when it is 4 cores (4 threads) and 5 cores (5 threads)? (No hyper threads)

The value set automatically is currently 1.

**Comment by Potothingi** [comment]
When I asked the Petal developers two years ago, they told me to use all available threads.

**Comment by Taiyou06** [comment]
The default value were never been 1 https://github.com/Winds-Studio/Leaf/blob/27134f699a8e1c75b6d080d1d6ad7001d3a2aa19/patches/server/0126-Multithreaded-Tracker.patch#L577 

0 automatically allocates quarter of your threads to the tracker (pathfinding's threading is 1/3 but you get the point.)
