### ISSUE TITLE
Optimize ServerLevel.tickNonPassenger() and ServerChunkCache.tick()

### ISSUE THREAD

**Issue by Godl1nk** [Dreeam-qwq/Leaf#168]
### What feature do you want to see added?

![image](https://github.com/user-attachments/assets/1246b5ea-2099-4d7e-9c4a-cbce92da900b)

this is a fork of leaf with my own optimizations 
further optimize this 2 method or any heavy methods in here.

**Comment by Dreeam-qwq** [comment]
What do you mean?

**Comment by Godl1nk** [comment]
? 可以对 ServerLevel.tickNonPassenger() 和 ServerChunkCache.tick() 做优化吗

**Comment by Dreeam-qwq** [comment]
> ? 可以对 ServerLevel.tickNonPassenger() 和 ServerChunkCache.tick() 做优化吗

No, it is impossible to optimize these “root” methods, since the real high costs or lag are not in these methods themselves.

If your server is lagging on Leaf, or you can confirm one Leaf’ s optimization or code is causing the lag, report to us and also provide the spark profiler.

**Comment by Godl1nk** [comment]
ya ik its those methods withing the method that lags, but ya if can optimize abit ty

**Comment by Dreeam-qwq** [comment]
> ya ik its those methods withing the method that lags, but ya if can optimize abit ty

We are always researching and adding new optimizations to Leaf. There is no need to open an enchantment request to request “Can you optimize here?”, unless you experience a really heavy tps drop?

And you can join our [discord server](https://discord.gg/gfgAwdSEuM). We have support forum in there. we can discuss there if your server has performance issue
