### ISSUE TITLE
Console error on shutdown

### ISSUE THREAD

**Issue by Pascalpex** [Dreeam-qwq/Leaf#17]
When shutting down the server using the `stop` command on Windows an error appears in the console
The error can be found in the log: https://pastebin.com/JsAd5MZA

This does not happen on Ubuntu and probably other Linux systems

This also does not happen when using [Gale 1.20.4](https://github.com/Dreeam-qwq/Gale)

**Comment by Dreeam-qwq** [comment]
Fixed in https://github.com/Dreeam-qwq/TerminalConsoleAppender/commit/af5a442f0a4976907962508200db7270bbbd4396 and https://github.com/Winds-Studio/Leaf/commit/223fdf3952fbd1f97052bdf3ad689711f98f45da

**Comment by Pascalpex** [comment]
Thank you
