### ISSUE TITLE
地图画插件渲染的地图无法正常显示

### ISSUE THREAD

**Issue by 404forever1** [Dreeam-qwq/Leaf#170]
paper可以正常工作
![image](https://github.com/user-attachments/assets/6903584a-4822-4846-b1b8-8f7c66829f51)

**Comment by Dreeam-qwq** [comment]
请按照问题模版反馈问题 https://github.com/Winds-Studio/Leaf/issues/new/choose

**Comment by Dreeam-qwq** [comment]
Moved to https://github.com/Winds-Studio/Leaf/issues/171
