### ISSUE TITLE
地图画插件无法正常渲染地图

### ISSUE THREAD

**Issue by 404forever1** [Dreeam-qwq/Leaf#171]
### 自我检查表

- [X] 我已经浏览过Issue, 并确保汇报的不是已知问题
- [ ] 我勾选了所有框, 因为我根本就没仔细看他们是什么
- [X] 我正在使用从 https://github.com/Winds-Studio/Leaf/releases 下载的最新 Leaf 构建
- [X] 我无法在 [Purpur 最新构建](https://purpurmc.org/) 上复现此问题

### 问题描述

地图画插件无法正常渲染地图
代码
![image](https://github.com/user-attachments/assets/41cc904e-2996-4395-a873-0d61371ca40d)
![image](https://github.com/user-attachments/assets/60a24e6a-4690-4011-a634-096820192681)

### 所期望的行为

正常显示

### 如何复现？

使用上述代码导入一个二维码解析链接

### Spark profiler 链接

不需要

**Comment by Dreeam-qwq** [comment]
`我勾选了所有框, 因为我根本就没仔细看他们是什么`
意义不明, 另外请提供spark profiler链接

**Comment by 404forever1** [comment]
> `我勾选了所有框, 因为我根本就没仔细看他们是什么` 意义不明, 另外请提供spark profiler链接

草

**Comment by DuoDuoJuZi** [comment]
spark链接，在交流群发过了，使用了最新构建且插件可在purpur2329最新构建正常使用
https://spark.lucko.me/gNWmkHB7Th

**Comment by 404forever1** [comment]
> `我勾选了所有框, 因为我根本就没仔细看他们是什么` 意义不明, 另外请提供spark profiler链接

修改了0 0

**Comment by 404forever1** [comment]
![image](https://github.com/user-attachments/assets/f5411fd1-46a3-48b3-a183-29668ce05f2c)
y已经解决，传值改为 0 0
