### ISSUE TITLE
Console log color missing since Leaf a3f3dba

### ISSUE THREAD

**Issue by HaHaWTH** [Dreeam-qwq/Leaf#175]
### Checklist

- [X] I have searched the existing issues
- [ ] I ticked all the boxes without actually reading them
- [X] I am using latest Leaf build from https://github.com/Winds-Studio/Leaf/releases
- [X] I tested and couldn't replicate this issue on [latest Purpur build](https://purpurmc.org/)

### What behaviour is observed?

Console log color is missing
![](https://i.ibb.co/5cN5gwX/IMG-5437.jpg)

### Expected behaviour

Logs are colored correctly

### To Reproduce

1. Install any plugins that print colored console logs(e.g. LuckPerms)
2. Launch the server
3. Colors are missing

### Spark profiler link

https://spark.lucko.me/WSH7RyMDtr

**Comment by sh2kcs** [comment]
+1

**Comment by HaHaWTH** [comment]
Related to https://github.com/PaperMC/Paper/issues/ 11637

**Comment by Dreeam-qwq** [comment]
Fixed in https://github.com/Winds-Studio/Leaf/pull/176
Can anyone have time to test? Thanks!
