### ISSUE TITLE
Performance analysis

### ISSUE THREAD

**Issue by Godl1nk** [Dreeam-qwq/Leaf#179]
### Checklist

- [X] I have searched the existing issues
- [ ] I ticked all the boxes without actually reading them
- [X] I am using latest Leaf build from https://github.com/Winds-Studio/Leaf/releases
- [X] I tested and couldn't replicate this issue on [latest Purpur build](https://purpurmc.org/)

### What behaviour is observed?

Well, i ran a smp server with a fork of leaf, im running with fine hardware but the mspt seems worrying for the playercount, can you guys help me give it a check on what is lagging and maybe give some advice ? well u can also use my spark profiler as to see what else can be optimized more, tysm.

### Expected behaviour

-

### To Reproduce

-

### Spark profiler link

[hidden]

### Error log (if applicable)

none

**Comment by Godl1nk** [comment]
heaviest is Sparky World Thread [play_world]

**Comment by Dreeam-qwq** [comment]
In Leaf config
```
create-snapshot-on-retrieving-blockstate: false
faster-random-generator.enabled: true
```

In paper world default config
`update-pathfinding-on-block-update: false`

**Comment by Godl1nk** [comment]
use Xoroshiro128PlusPlus ?

**Comment by HaHaWTH** [comment]
> use Xoroshiro128PlusPlus ?

Yes, and it’s the default random generator used in `faster-random-generator` option.

**Comment by Godl1nk** [comment]
x


18+mspt at 20 players hmm maybe its ok ? 
updated profiler

**Comment by Dreeam-qwq** [comment]
> https://spark.lucko.me/j8jL5T7C5e
> 
> 18+mspt at 20 players hmm maybe its ok ? updated profiler

The profiler link is expired, and It’s ok that the mspt is below 50, no need to think it is lagging

**Comment by Godl1nk** [comment]
d

here is the updated one, is it possible to skip most of the aiStep task or disable it if the mob is non-aware/has no ai

**Comment by andreasdc** [comment]
> https://spark.lucko.me/caoKil74zK
> 
> here is the updated one, is it possible to skip most of the aiStep task or disable it if the mob is non-aware/has no ai

Report to advancedplugins authot that they made not efficient plugin.
On the profiler it doesn't look like the server is lagging too, start the profiler with --thread * --combine-all and 2nd with --only-ticks-over 50
