### ISSUE TITLE
Please enable EntityTTL

### ISSUE THREAD

**Issue by Godl1nk** [Dreeam-qwq/Leaf#181]
### Checklist

- [X] I have searched the existing issues
- [ ] I ticked all the boxes without actually reading them
- [X] I am using latest Leaf build from https://github.com/Winds-Studio/Leaf/releases
- [X] I tested and couldn't replicate this issue on [latest Purpur build](https://purpurmc.org/)

### What behaviour is observed?

entity-timeouts dont wokr cause u never used it in the code.. please fix

### Expected behaviour

works

### To Reproduce

test

### Spark profiler link

no

**Comment by andreasdc** [comment]
Should work right? Set it to some low value and spawn some mobs to see if they will disappear.
![image](https://github.com/user-attachments/assets/2f6f524c-3616-4843-89fd-026511138257)

**Comment by Dreeam-qwq** [comment]
See above, it works fine.

**Comment by Godl1nk** [comment]
bro 
![image](https://github.com/user-attachments/assets/bae11a1d-56cc-4100-bae9-90e39def5f55)
the ttl field is not modified ?

**Comment by Godl1nk** [comment]
well ima make it so if its custom named it wont get despawn..

**Comment by andreasdc** [comment]
> well ima make it so if its custom named it wont get despawn..

It checks entity type, not the name, but you can check and send your results. 🚀

**Comment by Godl1nk** [comment]
![image](https://github.com/user-attachments/assets/a513d54f-ff11-4afc-81cc-efe9119ca5fb)
er no this is what i mean lmao
