### ISSUE TITLE
Wrong head rotation after entity is shown

### ISSUE THREAD

**Issue by andreasdc** [Dreeam-qwq/Leaf#182]
### Checklist

- [X] I have searched the existing issues
- [ ] I ticked all the boxes without actually reading them
- [X] I am using latest Leaf build from https://github.com/Winds-Studio/Leaf/releases
- [X] I tested and couldn't replicate this issue on [latest Purpur build](https://purpurmc.org/)

### What behaviour is observed?

When I am hidden from a player and I show myself to him, he sees my head rotation wrongly.

### Expected behaviour

Proper head rotation after entity is spawned.

### To Reproduce

1. Join on 2 Minecraft clients.
2. Hide yourself from 2nd player (hidePlayer method from a plugin)
3. Show yourself to the player.
4. Your head rotation is shown wrongly.

### Spark profiler link

-

**Comment by Dreeam-qwq** [comment]
You should provide the spark profiler link.
And can you replicate this issue if the mutlithreaded tracker is disabled?

**Comment by andreasdc** [comment]
I don't see this issue anymore, I have multithreaded tracker enabled, but for now it's good. 🤟
