### ISSUE TITLE
villager auto lock trading

### ISSUE THREAD

**Issue by Vuong26** [Dreeam-qwq/Leaf#185]
### Checklist

- [x] I have searched the existing issues
- [X] I ticked all the boxes without actually reading them
- [X] I am using latest Leaf build from https://github.com/Winds-Studio/Leaf/releases
- [X] I tested and couldn't replicate this issue on [latest Purpur build](https://purpurmc.org/)

### What behaviour is observed?

the villager auto get 1 exp after get a job so i cant change the trade

### Expected behaviour

if it was a feuture how to turn it off

### To Reproduce

villager go to a job block
get job and auto get 1 exp

### Spark profiler link

https://spark.lucko.me/SNoLiprdyW

**Comment by 5RoD** [comment]
I ticked all the boxes without actually reading them ✅✅✅✅✅

**Comment by Vuong26** [comment]
> I ticked all the boxes without actually reading them ✅✅✅✅✅

i update to 1.21.3 this morning and its fixed tks
