### ISSUE TITLE
other zombie types different speed

### ISSUE THREAD

**Issue by Karmelowy** [Dreeam-qwq/Leaf#19]
The other zombies than default one have super high movement speed

**Comment by Dreeam-qwq** [comment]
What do you mean other types of zombies?

**Comment by Karmelowy** [comment]
Desert and drowned

**Comment by Dreeam-qwq** [comment]
Fixed in df715cfa0f22ce41513a8ec8c489e7999627651b

But for those super speed zombies already spawned, you need to manually remove them, you can use command like `/kill @e[family=zombie]`
