### ISSUE TITLE
Powered Rails don't work

### ISSUE THREAD

**Issue by getxd-dev** [Dreeam-qwq/Leaf#2]
The title says it all, using the default config of Leaf.

**Comment by TH2403y** [comment]
You can try to modify some rail configuration at leaf.yml :） ，that can solve the problem

**Comment by Dreeam-qwq** [comment]
Fixed. I will readd powered rail opt patch after I fix it.

**Comment by Dreeam-qwq** [comment]
the `optimized PoweredRailBlock logic` patch is fixed and readded in 6fc1127ebba6ca9fc372cfb4cfabfff170159b35

And you can enable the `optimizedPoweredRails` in leaf.yml to use it.
