### ISSUE TITLE
[Feature] Backport MC-266334 fix of Mojang

### ISSUE THREAD

**Issue by HaHaWTH** [Dreeam-qwq/Leaf#20]
Mojang在23w51a修复了MC-266334 https://bugs.mojang.com/browse/MC-266334
该Bug会使潜影贝子弹可以损坏盔甲架，建议作为可选配置进行修复

或许有用的参考：https://github.com/HaHaWTH/Polpot/blob/ver/1.20.4/patches/server/0042-Fix-MC-266334.patch

**Comment by lilingfengdev** [comment]
我已在我的分支修复此BUG
