### ISSUE TITLE
JumpPads don't work

### ISSUE THREAD

**Issue by Pascalpex** [Dreeam-qwq/Leaf#24]
Plugins that modify the player velocity like jumppads or double jumps do not work on Leaf.
They do work on Purpur, Gale or PandaSpigot
Example Plugin: https://www.spigotmc.org/resources/custom-jumppads-1-8-1-19.44876/

**Comment by lilingfengdev** [comment]
可以给出日志吗(CN)
Can you give the logs (EN)

**Comment by Dreeam-qwq** [comment]
> 可以给出日志吗(CN) Can you give the logs (EN)

It’s an known issue, 0045-PandaSpigot-Configurable-knockback.patch causes it. I will check this during this weekend.

**Comment by Pascalpex** [comment]
The issue is no longer present in the latest version
