### ISSUE TITLE
絆線勾複製不了 The tripwire dupe fix is not reverted

### ISSUE THREAD

**Issue by TNTErick** [Dreeam-qwq/Leaf#3]
如題。用的是你們昨晚的最新版。
剛才睡不著就起來研究 tripwire dupe ，結果在服上試 (1.20.1 Purpur 2000) 不出來了就見到你們的這款。不過不得不說效能確實高。

## Desc of the bug:
The release version Leaf 1.20.1, doesnt revert the tripwire dupe fix. I've tried N-S, E-W orientation and wood-iron or 2 wood trapdoors, and none works. The both tripwire hooks just pop up like it does in PaperMC.

The same tests have been conducted in Vanilla 1.20.1 on my local machine and both orientations, wood-iron, at least one side duplicates.

## to replicate the bug:
in the game, assemble the machine, step onto and off from the tripwire.

Screenshots:
![2023-06-26_06 44 56](https://github.com/Winds-Studio/Leaf/assets/30978340/3db80f60-36c1-48a8-90f0-a5c93c5759f3)

**Comment by Dreeam-qwq** [comment]
Can you test it again in latest commit?
https://github.com/Winds-Studio/Leaf/suites/13853848776/artifacts/769551607

**Comment by TNTErick** [comment]
Yes. It works with the latest release. Now the SMP server owo.myftp.org is also deployed with Leaf. Thank you so much.
