### ISSUE TITLE
[Feature Request] Add ability to remove entity knockback

### ISSUE THREAD

**Issue by Dreeam-qwq** [Dreeam-qwq/Leaf#33]
Configurable remove entity knockback when gets attack.

**Comment by TheFloodDragon** [comment]
It seems better to adjust the knockback extent instead of removing it.

You can refer to [the solution of PandaSpigot](https://github.com/hpfxd/PandaSpigot/blob/master/patches/server/0015-Configurable-knockback.patch)

**Comment by Dreeam-qwq** [comment]
> It seems better to adjust the knockback extent instead of removing it.
> 
> You can refer to [the solution of PandaSpigot](https://github.com/hpfxd/PandaSpigot/blob/master/patches/server/0015-Configurable-knockback.patch)

This feature is different from the adjusting knockback. But it maybe added as a option to the knockback system.

Leaf do refer to the PandaSpigot's configurable knockback, [see this](https://github.com/Winds-Studio/Leaf/blob/ver/1.20.4/patches/unapplied/server/0048-PandaSpigot-Configurable-knockback.patch). but this patch has issues and can't work well on higher MC version, wait me to fix it.

**Comment by Dreeam-qwq** [comment]
Closed since no plan for this any more. Will reopen if anyone need this.
