### ISSUE TITLE
BUG / Compatibility issue

### ISSUE THREAD

**Issue by pjindras** [Dreeam-qwq/Leaf#37]
Plugins like Antivillager lag are not working,
The plugin should disable Villagers AI, when he has assigned a station, but AI is not disabled.

https://www.spigotmc.org/resources/antivillagerlag.102949/

Config:
https://paste.gg/p/anonymous/1d45b99ee8224a2481dff587a46fff6b

The same config on Purpur 1.20.4 works fine.

**Comment by Dreeam-qwq** [comment]
Can't reproduce on Leaf, you can try the latest version of Leaf to see if the issue still exist.
https://github.com/Winds-Studio/Leaf/releases/tag/ver-1.20.4

Test step:

1. Use your config
2. Spawn a villager using spawn egg
3. Use nametag to rename it as "Optimize"
4. Put a Lectern in front of it and it didn't become librarian and also can't trade.

btw, on Leaf, you don't need to install this plugin, if you have large amount of villagers in your server, you can enable `async_pathfinding` in leaf config

**Comment by pjindras** [comment]
Hello, yes, I use async_pathfinding, the plugin worked like it disabled villagers AI, when he has assignated a workstation (and with nametag, it is possible to enable it back), but I will test the latest version but we can close this if you want.
