### ISSUE TITLE
The author resells it for $100

### ISSUE THREAD

**Issue by CkaDebug** [Dreeam-qwq/Leaf#40]
![funny](https://github.com/Winds-Studio/Leaf/assets/141492699/8f31ddee-adad-4695-b65a-fed60dafc3b1)

**Comment by CkaDebug** [comment]
leaf owenr is idiot

**Comment by HaHaWTH** [comment]
WHAT THE....

**Comment by Dreeam-qwq** [comment]
What is "author resell", can't understand.

**Comment by lilingfengdev** [comment]
6

**Comment by liangcha385** [comment]
what?
