### ISSUE TITLE
async.async_entity_tracker and NPCs

### ISSUE THREAD

**Issue by pjindras** [Dreeam-qwq/Leaf#44]
Hello, 
async.async_entity_tracker should ignore NPCs, because it is not working properly with them.
While enabled, NPCs are randomly disappearing, but they should have extemp if possible.

**Comment by Dreeam-qwq** [comment]
Leaf's async entity tracker is not recommend to use right now, you should disable it.

**Comment by matipoirierg** [comment]
don't use citizens use fancynpcs instead

**Comment by Dreeam-qwq** [comment]
Can you test if you have free time (
https://github.com/Winds-Studio/Leaf/pull/109

**Comment by pjindras** [comment]
> Can you test if you have free time ( #109

I tested it, unfortunatelly issue with npcs presists,, some npcs are still not visible:

![image](https://github.com/user-attachments/assets/502d301c-fcd8-4627-886d-4a7f9095284b)

**Comment by Dreeam-qwq** [comment]
> > Can you test if you have free time ( #109
> 
> I tested it, unfortunatelly issue with npcs presists,, some npcs are still not visible:
> 
> ![image](https://private-user-images.githubusercontent.com/45400186/361125324-502d301c-fcd8-4627-886d-4a7f9095284b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxNzM1NjMsIm5iZiI6MTcyNTE3MzI2MywicGF0aCI6Ii80NTQwMDE4Ni8zNjExMjUzMjQtNTAyZDMwMWMtZmNkOC00NjI3LTg4NmQtNGE3ZjkwOTUyODRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAxVDA2NDc0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkwYWVmNTc2YjgyMTBhYmNlMTVjNjdkMDc4MDA0MmNkZWJkNTY2YWNkNTZlNDk1MGE5NTc2Y2ZkNzg1MjQ0MmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.N7adRG9zmED3uM8_oNuFis_VFmmk925w8vaaAfix8JA)

Try https://github.com/Winds-Studio/Leaf/actions/runs/10651777516/artifacts/1878950349

**Comment by pjindras** [comment]
> > > Can you test if you have free time ( #109
> > 
> > 
> > I tested it, unfortunatelly issue with npcs presists,, some npcs are still not visible:
> > ![image](https://private-user-images.githubusercontent.com/45400186/361125324-502d301c-fcd8-4627-886d-4a7f9095284b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxNzM1NjMsIm5iZiI6MTcyNTE3MzI2MywicGF0aCI6Ii80NTQwMDE4Ni8zNjExMjUzMjQtNTAyZDMwMWMtZmNkOC00NjI3LTg4NmQtNGE3ZjkwOTUyODRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTAxVDA2NDc0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkwYWVmNTc2YjgyMTBhYmNlMTVjNjdkMDc4MDA0MmNkZWJkNTY2YWNkNTZlNDk1MGE5NTc2Y2ZkNzg1MjQ0MmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.N7adRG9zmED3uM8_oNuFis_VFmmk925w8vaaAfix8JA)
> 
> Try https://github.com/Winds-Studio/Leaf/actions/runs/10651777516/artifacts/1878950349

It works perfect now

**Comment by Dreeam-qwq** [comment]
Async entity tracker is added back in https://github.com/Winds-Studio/Leaf/commit/43fae827ad82bf40c2eea4186a107b2bd48f1b89

Enable `async.async-entity-tracker.compat-mode` to fix visual issue related to Citizens's NPCs.
