### ISSUE TITLE
[Crash] when the server try to read a chunk data

### ISSUE THREAD

**Issue by pjindras** [Dreeam-qwq/Leaf#45]
https://paste.gg/p/anonymous/87fe38d23bf54453bc749186bd71d898

Java 21, minecraft 1.20.4

Nether world entity caused server crash, do you please know what could cause the crash or how to prevent this.
Thank you!

**Comment by Dreeam-qwq** [comment]
Server crashed when a player tried to teleport to his residence
![image](https://github.com/Winds-Studio/Leaf/assets/61569423/20f5e8d3-655d-401a-a6b4-0edd7412b420)

**Comment by pjindras** [comment]
Ok I removed the residence.

Thank you

**Comment by Dreeam-qwq** [comment]
> Ok I removed the residence.
> 
> Thank you

You don't need remove the plugin directly,,You can report this issue in residence's Github Issues, https://github.com/Zrips/Residence/issues

**Comment by pjindras** [comment]
Yes, I will report the issue, thank you.
