### ISSUE TITLE
[Bug] MythicMobs random spawn issue

### ISSUE THREAD

**Issue by Dreeam-qwq** [Dreeam-qwq/Leaf#48]
Try to fix MythicMobs random spawn issue caused by Pufferfish's async mob spawning?.

**Comment by 5RoD** [comment]
what exactly is the issue cuz mobs were spawning fine on my server

**Comment by postyizhan** [comment]
same problem

**Comment by Dreeam-qwq** [comment]
> same problem

Can you briefly describe how to reproduce?

**Comment by Dreeam-qwq** [comment]
Closed, since can't replicate on Leaf.
