### ISSUE TITLE
[Question] Should we drop bamboo collision patch?

### ISSUE THREAD

**Issue by HaHaWTH** [Dreeam-qwq/Leaf#56]
Since GeyserMC updated [Hurricane](https://github.com/GeyserMC/Hurricane/commit/de9ade84a1a38d7cbbd960cc92fa1f21c8d96ce7) and fixed bamboo collision in 1.20.5, I think there's no need to keep [this patch](https://github.com/Winds-Studio/Leaf/blob/ver/1.20.6/patches/server/0070-Configurable-bamboo-collision.patch).

**Comment by liangcha385** [comment]
将它同步到旧版本中？
_不过感觉不符合常理_
