### ISSUE TITLE
Should we fix NAN MineCarts issue?

### ISSUE THREAD

**Issue by liangcha385** [Dreeam-qwq/Leaf#57]
https://b23.tv/DPh6ENB
https://youtu.be/8nyPBhRTipI?si=JKNAJks6CO893OQT

**Comment by liangcha385** [comment]
or https://b23.tv/PKLVC6B

**Comment by Dreeam-qwq** [comment]
Can you reproduce it on Paper or Leaf?

**Comment by Dreeam-qwq** [comment]
Closed, since can't replicate on Paper or Leaf.
