### ISSUE TITLE
chatImage-protocol 模块有时会失效

### ISSUE THREAD

**Issue by liangcha385** [Dreeam-qwq/Leaf#59]
_失效链接 https://img-prod-cms-rt-microsoft-com.akamaized.net/cms/api/am/imageFileData/RE4wtc1?ver=9f09_
![image](https://github.com/Winds-Studio/Leaf/assets/108937242/aaac3533-401f-4b70-8a63-b500c93fcde6)
_未失效链接 https://web.hycdn.cn/arknights/official/pic/20240429/81c28e0e61c4c8c7c75107ff3e3a01ae.png_
![image](https://github.com/Winds-Studio/Leaf/assets/108937242/4c47e5d6-a1de-4f4c-ad5c-ea90c755a0bd)

初步推测可能与链接本身有关

**Comment by HaHaWTH** [comment]
Mod服务器上能否复现

**Comment by liangcha385** [comment]
无法在mod服务器上复现
![image](https://github.com/Winds-Studio/Leaf/assets/108937242/b3358312-5f31-4608-80ae-6602669e069c)
![image](https://github.com/Winds-Studio/Leaf/assets/108937242/dea16bad-7415-44ba-b530-f8a6344b4906)

**Comment by HaHaWTH** [comment]
模组版本是

**Comment by liangcha385** [comment]
> 模组版本是

ChatImage-1.2.4+1.20.4+fabric

**Comment by HaHaWTH** [comment]
Will be fixed in 1.20.6

**Comment by HaHaWTH** [comment]
Still reproducible?

**Comment by liangcha385** [comment]
> 仍然可重复？

The problem has been fixed
_I didn't use the latest version_

![5473e2a2abde234257f1cb99723fe8b9](https://github.com/Winds-Studio/Leaf/assets/108937242/23e200cc-a951-49cf-b5f5-8dbeccaa21b5)

**Comment by Dreeam-qwq** [comment]
> > 仍然可重复？
> 
> The problem has been fixed _I didn't use the latest version_
> 
> ![5473e2a2abde234257f1cb99723fe8b9](https://private-user-images.githubusercontent.com/108937242/346312371-23e200cc-a951-49cf-b5f5-8dbeccaa21b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAzMzAzNTIsIm5iZiI6MTcyMDMzMDA1MiwicGF0aCI6Ii8xMDg5MzcyNDIvMzQ2MzEyMzcxLTIzZTIwMGNjLWE5NTEtNDljZi1iNWY1LThkYmVjY2FhMjFiNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwN1QwNTI3MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yOTk0ZDc0MjJkY2I2ZmNkYmI3NDdhNDYyYjYwMTM4Yzk5NDI1MjYxZGEzMjg4NmZlYjRiNGRlYmUxYTVhMTdkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.IMv4Ml5jxmA9922bU2CIORXGLF1-NKVKG4nRtMcvuC8)

Well, thanks your testing~
