### ISSUE TITLE
Crash when launching latest Leaf build

### ISSUE THREAD

**Issue by HaHaWTH** [Dreeam-qwq/Leaf#60]
### Environment:

Windows Server 2022
Azul zulu JDK 21.0.2

Leaf commit: 90732ec

## Reproduce steps:

1. Download [Leaf (commit 90732ec)](https://github.com/Winds-Studio/Leaf/actions/runs/9173838236/artifacts/1522697328)
2. Start the server
3. See error and crashed

### Error logs:

https://mclo.gs/UJ2r950

**Comment by ghost** [comment]
[22:26:22 WARN]: Failed to load datapacks, can't proceed with server load. You can either fix your datapacks or reset to vanilla with --safeMode

**Comment by HaHaWTH** [comment]
> [22:26:22 WARN]: Failed to load datapacks, can't proceed with server load. You can either fix your datapacks or reset to vanilla with --safeMode

That's a fresh-boot, all datapacks are built-in.
Also I tried --safeMode, does not work:/

**Comment by envizar** [comment]
Same error, no datapacks

**Comment by Dreeam-qwq** [comment]
Any plugin? Default config (Paper/Leaf)?

**Comment by HaHaWTH** [comment]
> Any plugin? Default config (Paper/Leaf)?

Only spark is present. Configurations are all default.

**Comment by ghost** [comment]
![Screenshot_6](https://github.com/Winds-Studio/Leaf/assets/108226177/0fa96fdc-4cf4-44ae-9be1-034551f623ed)
sounds good?

**Comment by Dreeam-qwq** [comment]
Fixed in 7bb67dee00b056d89a4f286ac07d42cd84a1a34c
