### ISSUE TITLE
[feature request] Config option to completely disable join/leave messages

### ISSUE THREAD

**Issue by envizar** [Dreeam-qwq/Leaf#64]
Plugins that remove join/leave messages are disabled when the server is stopped
But a few seconds after disabling the plugins, the players are still on the server and can see the chat
Vanish plugins are already disabled and can't hide leave messages for vanished players. So players can see names of vanished players for a moment
This is a problem for some servers, so I want to see a configuration option for leaf to completely disable join/leave messages

**Comment by Dreeam-qwq** [comment]
Add in 235fc5298bd65727e7e5ab0dbc27a935a686e9ba
Set `misc.connection_message.quit.enabled` and `misc.connection_message.quit.enabled` in leaf config to false to disable join/leaves message
