### ISSUE TITLE
Typewriter不干活

### ISSUE THREAD

**Issue by postyizhan** [Dreeam-qwq/Leaf#7]
Typewriter:https://github.com/gabber235/TypeWriter/tree/v0.3.1
![3c98da8da7de7970af4de80d1b3dd917](https://github.com/Winds-Studio/Leaf/assets/97342038/6da6dca2-46e5-492e-ad6f-1550b6c463fd)

**Comment by Dreeam-qwq** [comment]
Fixed in plugin side https://github.com/gabber235/TypeWriter/pull/67
