### ISSUE TITLE
[试着去支持Forge模组?]

### ISSUE THREAD

**Issue by DNPHINTI** [Dreeam-qwq/Leaf#70]
模仿Mohist试着

**Comment by lilingfengdev** [comment]
老哥，你知道你在说什么吗？

**Comment by HaHaWTH** [comment]
wat...

**Comment by HaHaWTH** [comment]
Hello!

Thank you for your suggestion and interest in having Leaf support Forge mods. We appreciate your enthusiasm and the time you’ve taken to reach out to us.

However, we regret to inform you that it is not feasible for our plugin server to support Forge mods at this time. Here are a few reasons for this decision:

	1.	Architectural Differences: Our plugin server and Forge mods operate on fundamentally different architectures. Integrating them would require extensive modifications to both the server and the mods, which is beyond our current scope and resources.
	2.	Maintenance and Stability: Ensuring compatibility between plugins and mods would necessitate continuous updates and maintenance. This could compromise the stability and reliability of our server, which we prioritize highly for all users.
	3.	Performance Concerns: Combining plugins and Forge mods could introduce significant performance overhead and potential conflicts, leading to a suboptimal experience for our users.

For those interested in both plugins and Forge mods, we recommend exploring existing hybrid server solutions like Mohist, which are specifically designed to support both. These solutions might offer the functionalities you’re looking for.

We hope you understand our position. If you have any other suggestions or need assistance with anything else, please feel free to let us know.

Best regards,

HaHaWTH

**Comment by Dreeam-qwq** [comment]
所以为什么不用mohist？

插件服核心和mod服(混合)核心是两种东西
