### ISSUE TITLE
/perf command not working

### ISSUE THREAD

**Issue by NanKillBro** [Dreeam-qwq/Leaf#71]
![image](https://github.com/Winds-Studio/Leaf/assets/72297072/159ee837-2b64-411c-9caa-d06f661b7e07)

**Comment by NanKillBro** [comment]
Server is running version Leaf version git-Leaf-"504935f" (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 504935f on ver/1.20.4)
With no plugin

**Comment by Dreeam-qwq** [comment]
vanilla profiler is deleted, use spark instead
