### ISSUE TITLE
Console formatting is broken in Pterodactyl

### ISSUE THREAD

**Issue by zohfur** [Dreeam-qwq/Leaf#73]
![image](https://github.com/Winds-Studio/Leaf/assets/6598846/6a57bece-a4aa-434a-9a16-bb056bd54c3c)
![image](https://github.com/Winds-Studio/Leaf/assets/6598846/c575efaf-3238-4244-a63f-08367292329b)

All console output just overwrites the same two lines. This only seems to start after plugin remapping completes. I do not have this issue with any other Paper binary or fork, I have only experienced this when running the Leaf 1.21 binary. I am unsure if this behavior happens in any other server host platforms, I tested locally in Powershell and a Linux terminal but did not get this behavior.

![image](https://github.com/Winds-Studio/Leaf/assets/6598846/6990b015-1aaa-4c1b-a04c-604a37780bd8)

**Comment by zohfur** [comment]
https://github.com/Winds-Studio/Leaf/assets/6598846/f58f9dc8-f59b-467b-bf3b-14d2b1afa4e9

**Comment by T14D3** [comment]
Add `-Dterminal.jline=false -Dterminal.ansi=true` to your startup flags, will fix the issue

**Comment by Dreeam-qwq** [comment]
↑ solution

**Comment by zohfur** [comment]
Ah yep, I couldn't remember which flag it was. That seems to have fixed an issue, but it's likely still a bug with Leaf. Might want to add a note to the Readme for pterodactyl users or fix the underlying issue. Otherwise feel free to close :)

**Comment by Dreeam-qwq** [comment]
Fixed in fac22f81bc8c47229c6c4bec023a0097aca457b2

Can you remove `-Dterminal.jline=false -Dterminal.ansi=true` these two flags and test this new build to see the issue fixed?

**Comment by zohfur** [comment]
Yep, the new build fixes the issue. It also fixed another issue I was going to post which caused the FAWE plugin to fail remapping, but everything is working great now. Fantastic work.
