### ISSUE TITLE
1.20.4 leaf - Mobs can ghost

### ISSUE THREAD

**Issue by Athamex** [Dreeam-qwq/Leaf#76]
https://github.com/Winds-Studio/Leaf/assets/85680645/09ceed9c-bbb1-4a02-8d75-3503050f3ee7

https://github.com/Winds-Studio/Leaf/assets/85680645/5ea03e72-96b1-4e34-9454-d8e8607f7f16

**Comment by Dreeam-qwq** [comment]
Fixed in https://github.com/Winds-Studio/Leaf/commit/1caf18d0e1fe078155a111ca159272117c89cd9a
