### ISSUE TITLE
Plugin Compatibility

### ISSUE THREAD

**Issue by Toriko199** [Dreeam-qwq/Leaf#79]
Hello! heard that ModelEngine is supporting 1.20.6 so I downloaded it and try it out, but sadly it doesn't even be able to load.
I've try it on Purpur and Paper and it work fine

Full log: [latest.log](https://github.com/user-attachments/files/16124487/latest.log)
Leaf version: 1.20.6-DEV-ver/1.20.6@f0e36a8 (2024-07-04T12:42:14Z) (Implementing API version 1.20.6-R0.1-SNAPSHOT)

**Comment by Dreeam-qwq** [comment]
Use leaf-1.20.6-mojmap instead of reobf https://github.com/Winds-Studio/Leaf/releases/download/ver-1.20.6/leaf-1.20.6-mojmap.jar

**Comment by Toriko199** [comment]
> Use leaf-1.20.6-mojmap instead of reobf https://github.com/Winds-Studio/Leaf/releases/download/ver-1.20.6/leaf-1.20.6-mojmap.jar

oh! it worked tysm, sorry I didn't know about this
