### ISSUE TITLE
We cannot trade with villager

### ISSUE THREAD

**Issue by RunqRun** [Dreeam-qwq/Leaf#8]
![image](https://github.com/Winds-Studio/Leaf/assets/91005690/b3b08207-b5ab-40c2-91cc-db2d271cbb63)
I attached the image when we cannot trade some item with villager.

**Comment by RunqRun** [comment]
Leaf version is 1.20.2
https://github.com/Winds-Studio/Leaf/commit/31990e0284ab6c28a637f2ceebd2736cd5cd2992

**Comment by Dreeam-qwq** [comment]
Fixed in latest commit of 1.20.2 branch. cb51f2c
