### ISSUE TITLE
[Leaf 1.21] Exception ticking world when async-mob-spawn enabled

### ISSUE THREAD

**Issue by HaHaWTH** [Dreeam-qwq/Leaf#82]
**Environment:**

Azul zulu JDK 21.0.3

**Leaf version:**

Leaf 1.21 (commit: 7749c26)

**Reproduce steps:**
1. Start Leaf 1.21 (7749c26)
2. Try teleporting/other operations with large chunk updates
3. Server crashed

**Error logs:**

https://mclo.gs/7yrwGv3

**Comment by Dreeam-qwq** [comment]
Fixed in cc42043596b818535b98077824a510e185226796

**Comment by Dreeam-qwq** [comment]
try ed3cd2c72c44b5e0fe9663295ada6903f344dfd4
