### ISSUE TITLE
最新版本分类机无法正常运作

### ISSUE THREAD

**Issue by liyulong-sgy** [Dreeam-qwq/Leaf#83]
粘液块弹射物品流至漏斗假设漏斗有10个不会漏到第一个或者前三个及以上会漏到最后一个漏斗或倒数第三个或四个

**Comment by HaHaWTH** [comment]
Leaf版本 (/version 命令输出)
配置文件 (config文件夹内gale和leaf的配置文件)
复现步骤 (最好为视频)

**Comment by HaHaWTH** [comment]
gale-world-default.yml中的
check-nearby-item

hopper.interval
minecart.interval
改为1后再试
