### ISSUE TITLE
[Feature Request]Add configurable secureseed patches

### ISSUE THREAD

**Issue by HaHaWTH** [Dreeam-qwq/Leaf#9]
Hi Dreeam,
Leaf is incredibly great, but I hope you can add the patches of secure seed to prevent seed hacks and make it as optional. This will make Leaf more perfect :)
Here are some implementation links:
1.[Earthcomputer/SecureSeed](https://github.com/Earthcomputer/SecureSeed)
2.[Matter](https://github.com/plasmoapp/matter)
btw, is there Alternate Current patches in Leaf? Sincerely hope this can be ported into Leaf as an option.
Thanks a lot ❤

**Comment by Dreeam-qwq** [comment]
Alternate Current is integrated in Paper, you can refer to https://docs.papermc.io/paper/reference/world-configuration#misc_redstone_implementation , by setting `redstone-implementation: alternate-current` in paper-world-default.yml to enable this. But I personally don't recommend to use alternate-current implementation, since it will break so many redstone machines.

**Comment by HaHaWTH** [comment]
Thanks a lot, how about the secure seed implementation? I think many survival server owners will need this.🧐

**Comment by Dreeam-qwq** [comment]
> Thanks a lot, how about the secure seed implementation? I think many survival server owners will need this.🧐

Will do this during this weekend.

**Comment by Dreeam-qwq** [comment]
Leaf with secure seed implementation https://github.com/Winds-Studio/Leaf/actions/runs/6481021718

Still need time to figure out how to make it configurable.((

**Comment by HaHaWTH** [comment]
Nice! 👍btw will Lithium be implemented in Leaf?

**Comment by Dreeam-qwq** [comment]
> Nice! 👍btw will Lithium be implemented in Leaf?

I have no plan for this yet, but Leaf's upstream (Gale) already include some Lithium patches.

**Comment by Dreeam-qwq** [comment]
Added in 7c66d13579bd14bdd3ea2e6d1dce3217d97b6818
