### ISSUE TITLE
Food is eaten with normal speed with low tick rate

### ISSUE THREAD

**Issue by PukPukov** [Dreeam-qwq/Leaf#90]
The food is consumed at a normal speed with a low tick rate (caused not by server overloading but by the use of the /tick rate command), while it should be consumed more slowly, corresponding to the server tick rate.

**Comment by HaHaWTH** [comment]
https://github.com/PaperMC/Paper/blob/master/patches/server/1034-Lag-compensation-ticks.patch

Paper has lag compensation for food eating.

**Comment by PukPukov** [comment]
> https://github.com/PaperMC/Paper/blob/master/patches/server/1034-Lag-compensation-ticks.patch
> 
> Paper has lag compensation for food eating.

Well...
