### ISSUE TITLE
java.io.NotSerializableException: org.bukkit.craftbukkit.entity.CraftVillager$CraftProfession

### ISSUE THREAD

**Issue by QuQuShKa1205** [Dreeam-qwq/Leaf#92]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What behaviour is observed?

When killing a villager, this error appears. Only with CoreProtect plugin

### Expected behaviour

dd

### To Reproduce

1. put the coreprotect plugin on the server
2. kill a villager
3. error in the console

### Plugin list

Only CoreProtect

### Leaf Version

1.21-DEV-ver/1.21@d4fcc79

### Error log (if applicable)

https://mclo.gs/EReY2pN

### Configuration

https://paste.gg/p/anonymous/4d63e3c0948e43dabfd365912fec724b

**Comment by Dreeam-qwq** [comment]
Update your CoreProtect to latest build. This error is fixed on latest commit of CoreProtect main branch.
