### ISSUE TITLE
[Question] how much does this change redstone

### ISSUE THREAD

**Issue by ghost** [Dreeam-qwq/Leaf#93]
in one server implementation that this uses patches from says the redstone implementation in it is based on alternate current and that has vanilla behavior so I'm curios if this also has vanilla behavior redstone

edit: I'm specifically asking about 1.21 newest version

**Comment by TH2403y** [comment]
He affects designs that require a specific redstone update direction. For example ，some TNT Duper will be unable to work as a result , For normal players, It's nothing. If you have a redstone server, don't enable it.

**Comment by HaHaWTH** [comment]
For more info, see SpaceWalkerRS/alternate-current#23
