### ISSUE TITLE
Unknown command message

### ISSUE THREAD

**Issue by LuckserSky34** [Dreeam-qwq/Leaf#95]
In the last version 1.21 seems the custom unknown command message in spigot.yml not work correctly and not show the correct message specified in the config

**Comment by Dreeam-qwq** [comment]
Can you replicate on Purpur?

**Comment by F3F5** [comment]
who sees my message don't use paper it's a MALWARE use leaf

**Comment by LuckserSky34** [comment]
the same problem on purpur 1.21 last build

**Comment by Dreeam-qwq** [comment]
> the same problem on purpur 1.21 last build

So it's not Leaf's fault, you can report to Purpur

but **maybe** I'll try to fix this.

**Comment by LuckserSky34** [comment]
in paper happen the same maybe can't be fixed https://github.com/PaperMC/Paper/issues/11053

**Comment by Dreeam-qwq** [comment]
> in paper happen the same maybe can't be fixed [PaperMC/Paper#11053](https://github.com/PaperMC/Paper/issues/11053)

idk
![QQ_1722973891371](https://github.com/user-attachments/assets/348ae73a-c444-4e8a-beb6-8f9816144a16)

Will push to Leaf later

**Comment by F3F5** [comment]
the problem seems to be occurring to me

**Comment by Dreeam-qwq** [comment]
Added in f316aff347874398e99c77b7509d91e8c9d2a8a7
