### ISSUE TITLE
Lava has no damage

### ISSUE THREAD

**Issue by RanMinecraft** [Dreeam-qwq/Leaf#97]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What behaviour is observed?

some of chunks lava has no damage

### Expected behaviour

lava should damage player

### To Reproduce

1. /gamemode survival
2. jump in to lava

### Plugin list

nothing

### Leaf Version

This server is running Leaf version 1.21-DEV-ver/1.21@2149923 (2024-08-06T18:25:17Z) (Implementing API version 1.21-R0.1-SNAPSHOT) * You are 1 version(s) behind Download the new version at: https://github.com/Winds-Studio/Leaf Previous: 1.21-DEV-d4fcc79 (MC: 1.21)

https://github.com/user-attachments/assets/2c633b60-acaf-4333-8662-7b1dcb894f2e

**Comment by Dreeam-qwq** [comment]
Seems related to [Reduce-entity-fluid-lookups-if-no-fluids.patch](https://github.com/Dreeam-qwq/Gale/blob/ver/1.21/patches/server/0033-Reduce-entity-fluid-lookups-if-no-fluids.patch) (refer to https://github.com/LeavesMC/Leaves/issues/277), but I can't replicate this (

**Comment by HaHaWTH** [comment]
* You are 1 version(s) behind

**Comment by RanMinecraft** [comment]
> * You are 1 version(s) behind

its from [relse](https://github.com/Winds-Studio/Leaf/releases/tag/ver-1.21)
latest version

**Comment by RanMinecraft** [comment]
it happen a lot , download from release just now but 1 version behind

> > * You are 1 version(s) behind
> 
> its from [relse](https://github.com/Winds-Studio/Leaf/releases/tag/ver-1.21) latest version

**Comment by RanMinecraft** [comment]
should i download from action?

**Comment by Dreeam-qwq** [comment]
> should i download from action?

They are same version

**Comment by RanMinecraft** [comment]
> > should i download from action?
> 
> They are same version
![image](https://github.com/user-attachments/assets/473fd08e-bcc9-4636-9871-4a9ce32dfaf9)

This server is running Leaf version 1.21-DEV-ver/1.21@5692cf0 (2024-08-09T11:56:14Z) (Implementing API version 1.21-R0.1-SNAPSHOT)
* You are 3 version(s) behind
Download the new version at: https://github.com/Winds-Studio/Leaf
Previous: 1.21-DEV-dbfeb87 (MC: 1.21)

**Comment by Dreeam-qwq** [comment]
> > > should i download from action?
> > 
> > 
> > They are same version
> > ![image](https://private-user-images.githubusercontent.com/69817107/356704059-473fd08e-bcc9-4636-9871-4a9ce32dfaf9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyMjY4NzgsIm5iZiI6MTcyMzIyNjU3OCwicGF0aCI6Ii82OTgxNzEwNy8zNTY3MDQwNTktNDczZmQwOGUtYmNjOS00NjM2LTk4NzEtNGE5Y2UzMmRmYWY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA5VDE4MDI1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg3MTgzZjVkOWQ3NDM4NTRiM2ViOWU4ZDZmMGRhY2FlMDc4YTBiMGEwMzg2ODRmZGE4NjczYmNiMDRkMGQzM2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Y-igmJ1zMCmc2BJymhz6401mtOP1sPgBfct-HTCz17o)
> 
> This server is running Leaf version 1.21-DEV-ver/1.21@5692cf0 (2024-08-09T11:56:14Z) (Implementing API version 1.21-R0.1-SNAPSHOT)
> 
> * You are 3 version(s) behind
>   Download the new version at: https://github.com/Winds-Studio/Leaf
>   Previous: 1.21-DEV-dbfeb87 (MC: 1.21)

Still can replicate on this version? 100% or frequently

**Comment by RanMinecraft** [comment]
> > > > should i download from action?
> > > 
> > > 
> > > They are same version
> > > ![image](https://private-user-images.githubusercontent.com/69817107/356704059-473fd08e-bcc9-4636-9871-4a9ce32dfaf9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyMjY4NzgsIm5iZiI6MTcyMzIyNjU3OCwicGF0aCI6Ii82OTgxNzEwNy8zNTY3MDQwNTktNDczZmQwOGUtYmNjOS00NjM2LTk4NzEtNGE5Y2UzMmRmYWY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA5VDE4MDI1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg3MTgzZjVkOWQ3NDM4NTRiM2ViOWU4ZDZmMGRhY2FlMDc4YTBiMGEwMzg2ODRmZGE4NjczYmNiMDRkMGQzM2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Y-igmJ1zMCmc2BJymhz6401mtOP1sPgBfct-HTCz17o)
> > 
> > 
> > This server is running Leaf version 1.21-DEV-ver/1.21@5692cf0 (2024-08-09T11:56:14Z) (Implementing API version 1.21-R0.1-SNAPSHOT)
> > 
> > * You are 3 version(s) behind
> >   Download the new version at: https://github.com/Winds-Studio/Leaf
> >   Previous: 1.21-DEV-dbfeb87 (MC: 1.21)
> 
> Still can replicate on this version? 100% or frequently

yes, and frequently

**Comment by Dreeam-qwq** [comment]
can't replicate

**Comment by MC-XiaoHei** [comment]
try to make a replicated world?

**Comment by Radiation-pi** [comment]
Try to confirm that your plugins doesn't cancel the damage. Some plugins like ESS or CMI can make ops like the god and prevent ops from any damage.

**Comment by Dreeam-qwq** [comment]
Closed since can not replicate. Welcome to reopen it if you met this issue on latest Leaf 1.21.1 (and also provide steps to replicate and link of spark profiler).
