### ISSUE TITLE
Add an option to convert worlds from the MCA format to Linear Automatically in leaf-global.yml

### ISSUE THREAD

**Issue by PythonChicken123** [Dreeam-qwq/Leaf#98]
### What feature do you want to see added?

Please add the auto convert to MCA (Anvil format) to Linear format feature. You can add the `misc.auto-convert-anvil-to-linear` line in leaf-global.yml to add the option. I see LeavesMC (A PaperMC fork) already has this feature in their [leaves.yml](https://docs.leavesmc.org/en/leaves/reference/configuration) on their documentation. I hope you add this feature as soon as possible. Thanks for reviewing!

**Comment by Dreeam-qwq** [comment]
You can use this tool https://github.com/xymb-endcrystalme/LinearRegionFileFormatTools to convert manually
