### ISSUE TITLE
无法挽回的崩服

### ISSUE THREAD

**Issue by CN-swa** [Dreeam-qwq/Leaf#99]
我原来使用paper、purpur开服都没有问题的，这次仅是服务端核心替换成了Leaf控制台就出现了许多报错，具体如https://mclo.gs/g2Iuof3 ，如果您看到了，麻烦您帮助我，在此感谢了！
使用的版本:Leaf 1.19.4
Java环境：zulu jdk 21

**Comment by CN-swa** [comment]
我的服务器是群组服，我将每个子服都替换成了Leaf，但每个子服都出现了相同状况的报错
其中每个子服都具有的相同的插件：
ViaVersion-5.0.3
ViaRewind-4.0.2
ViaBackwards-5.0.3
CMILib1.4.4.6
Multiverse-Core-4.3.1
PlaceholderAPI-2.11.3
ProtocolLib
Citizens-2.0.31-b3101
并且我还在几个子服中使用了数据库

**Comment by Dreeam-qwq** [comment]
Leaf1.19.4不受支持，推荐用Leaf1.21

**Comment by CN-swa** [comment]
可是许多插件都还没有更新1.21

**Comment by Dreeam-qwq** [comment]
> 可是许多插件都还没有更新1.21

那你用purpur好了(
